### ISSUE TITLE
Error on Waybar

### ISSUE THREAD

**Issue by 4Gettt25** [dav-med/dotfiles#1]
**Describe the bug**
Error when logging "Config error at line 39 (~/.config/hypr/hyprland.conf): Error setting value <XCURSOR_SIZE, 32> for field <env>: No such field. Hyprland may not work correctly

**To Reproduce**
1. clone repository 
2. execute install.sh
3. restart and switch to Hyprland (Wayland)

**Desktop (please complete the following information):**
 - OS: [ArcoLinux]
 - Kernel [6.2.7-arch 1-1 64-bit]

**Comment by dav-med** [comment]
Removed XCURSOR settings to let it be handled by gtk/kde on their specific configs to avoid issues and redundancy.
